---
title: "Datos NASDAQ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(quantmod)
library(xml2)
library(rvest)
library(openxlsx)
library(dplyr)
```

```{r}

mdate="2019-01-01"
SCOB=getSymbols('SCOB', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
NMRD=getSymbols('NMRD', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
FEYE=getSymbols('FEYE', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
BSBK=getSymbols('BSBK', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
SLAB=getSymbols('SLAB', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
OPTN=getSymbols('OPTN', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
NVCR=getSymbols('NVCR', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
BBI=getSymbols('BBI', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
AGNC=getSymbols('AGNC', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
SCR=getSymbols('SCR', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
ESXB=getSymbols('ESXB', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
IFRX=getSymbols('IFRX', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
CVCO=getSymbols('CVCO', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
NVEC=getSymbols('NVEC', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
NMRK=getSymbols('NMRK', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
BBQ=getSymbols('BBQ', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
FNLC=getSymbols('FNLC', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
FNKO=getSymbols('FNKO', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
TWST=getSymbols('TWST', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
SCOR=getSymbols('SCOR', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
AGLE=getSymbols('AGLE', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
STRT=getSymbols('STRT', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
NVCN=getSymbols('NVCN', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
SDC=getSymbols('SDC', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
SDH=getSymbols('SDH', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
KLXE=getSymbols('KLXE', from=mdate, auto.assign = F)[,4]

mdate="2019-01-01"
CMRX=getSymbols('CMRX', from=mdate, auto.assign = F)[,4]
```


```{r}
IXIC <- merge(AGLE,AGNC,BBI,BBQ,BSBK,CMRX,CVCO,ESXB,FEYE,FNKO,FNLC,IFRX,KLXE,NMRK,NVCN,NVCR,NVEC,OPTN,SCOB,SCOR,SCR,SDC,SDH,SLAB,STRT,TWST)
```

```{r}
write.xlsx(IXIC, "IXIC.xlsx")
```




```{r}
IXIC=data.frame(
AGLE=AGLE,
AGNC=AGNC,
BBI=BBI,
BBQ=BBQ,
BSBK=BSBK,
CMRX=CMRX,
CVCO=CVCO,
ESXB=ESXB,
FEYE=FEYE,
FNKO=FNKO,
FNLC=FNLC,
IFRX=IFRX,
KLXE=KLXE,
NMRK=NMRK,
NVCN=NVCN,
NVCR=NVCR,
NVEC=NVEC,
OPTN=OPTN,
SCOB=SCOB,
SCOR=SCOR,
SCR=SCR,
SDC=SDC,
SDH=SDH,
SLAB=SLAB,
STRT=STRT,
TWST=TWST)
```

